server:
  port: 7303

spring:
  application:
    name: sentinel-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719


#对Feign的支持
feign:
  sentinel:
    enabled: true
