server:
  port: 7107
spring:
  application:
    name: hystrix-service-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/


feign:
  hystrix:
    enabled: true
hystrix:
   command:
     default:
       execution:
        isolation:
         thread:
          timeoutInMilliseconds: 2000

