server:
  port: 7301

spring:
  application:
    name: sentinel-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #服务注册中心地址
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口




